#!/bin/bash

#################
#               #
#    PLEASE!    #
#               #
#################

#
#    VARIABLES
#

PLS_DEV=1
PLS_FILE="$HOME/.please"
PLS_FILE_COMMENT="# please, look at your collected terminal one-liners ..."
PLS_ALIAS="alias pls='pwd' # comment"
PLS_BASHRC="$HOME/.bashrc"
PLS_MSG_PREFIX="「please」"
PLS_MSG_INIT_ALREADY="$PLS_MSG_PREFIX I found '$PLS_FILE' - apparently 'please' is already initialized!"
PLS_MSG_INIT_OK="$PLS_MSG_PREFIX successfully initialized! Please start a fresh terminal or run 'exec bash' to start using 'please'."

#
#    VARIABLES IN DEV MODE
#

if [ "$PLS_DEV" -eq 1 ]; then
    echo "$PLS_MSG_PREFIX running in DEV mode"
    # modify some values for development
    PLS_FILE="dev/.please"
    PLS_ALIAS="alias pls='pwd' # comment"
    PLS_BASHRC="dev/.bashrc"
fi

#
#    FUNCTIONS
#

# FUNCTION: help
pls_help() {
    # TODO
    echo "$PLS_MSG_PREFIX help... (WIP)"
    exit 1
}

# FUNCTION: initialize
pls_init() {
    if [ -f "$PLS_FILE" ]; then
        echo "$PLS_MSG_INIT_ALREADY"
        exit 1
    else
        # create .please file with comment in $HOME
        echo "$PLS_FILE_COMMENT" >> "$PLS_FILE"
        # append alias to .bashrc
        echo "$PLS_ALIAS" >> "$PLS_BASHRC"
        echo "$PLS_MSG_INIT_OK"
        exit 0
    fi
}

#
#    PARSE ARGS
#

# TEST: no args?
[ $# -eq 0 ] && pls_help

# TEST: initialize?
[ "$1" = "initialize" ] && pls_init