#!/bin/bash

#################
#               #
#  Oh, PLEASE!  #
#               #
#################

#
#    DEV MODE ON / OFF
#

PLS_DEV=0 # ON (1) or OFF (0)

#
#    TEXT FORMATTING CODES (in case it's supported by the terminal)
#

TF_X="\033[0m" # unset all styles
TF_XC="\033[39m" # unset color
TF_GREEN="\033[32m" # set foreground color to green
TF_RED="\033[31m" # set foreground color to red
TF_BOLD="\033[1m" # set text style to bold
TF_DIM="\033[2m" # set text style to dim
TF_BLINK="\033[25m" # set text style to blink

#
#    VARIABLES
#

PLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # thanks to https://stackoverflow.com/a/246128
PLS_FILE="${HOME}/.please"
PLS_ALIAS="alias please="${PLS_DIR}/please" # please don't remove this comment, please"
PLS_BASHRC="${HOME}/.bashrc"
PLS_DELIMITER=": "
PLS_MSG_PREFIX="${TF_GREEN}${TF_BOLD}⸢please⸥${TF_X}"

#
#    SET UP DEV MODE
#

if [ "${PLS_DEV}" -eq 1 ]; then
    # modify some values for development
    PLS_FILE="${PLS_DIR}/dev/.please"
    PLS_BASHRC="${PLS_DIR}/dev/.bashrc"
fi

#
#    FUNCTIONS
#

# FUNCTION: help
function pls_help() {
    echo -e "${PLS_MSG_PREFIX} ${TF_DIM}let me show you the available commands:${TF_X}"
    echo -e "${TF_BOLD}${TF_GREEN}  ⤳ ${TF_X}${TF_GREEN}please note how to ${TF_RED}<description>${TF_X} : let ${TF_BOLD}please${TF_X} note a new one-liner"
    echo -e "${TF_BOLD}${TF_GREEN}  ⤳ ${TF_X}${TF_GREEN}please look for ${TF_RED}<keyword>${TF_X}        : let ${TF_BOLD}please${TF_X} look for a note containing <keyword>"
    echo -e "${TF_BOLD}${TF_GREEN}  ⤳ ${TF_X}${TF_GREEN}please please${TF_X}                    : don't use this command!"
    echo -e "${TF_BOLD}${TF_GREEN}  ⤳ ${TF_X}${TF_GREEN}please help${TF_X}                      : just try and see what happens!"
    echo -e "${TF_BOLD}${TF_GREEN}  ⤳ ${TF_X}${TF_GREEN}please uninstall yourself${TF_X}        : remove ${TF_BOLD}please${TF_X} command from system"
    echo -e "${TF_BOLD}${TF_GREEN}  ⤳ ${TF_X}${TF_GREEN}./please install yourself${TF_X}        : initially install ${TF_BOLD}please${TF_X}"
}

# FUNCTION: help
function pls_is_installed() {
    if grep -q "${PLS_ALIAS}" "${PLS_BASHRC}" && [ -f "${PLS_FILE}" ]; then
        return 0
    else
        return 1
    fi
}

# FUNCTION: install
function pls_install() {
    if pls_is_installed; then
        echo -e "${PLS_MSG_PREFIX} is apparently ${TF_BOLD}already installed!${TF_X}"
        exit 1
    else
        echo -e "${PLS_MSG_PREFIX} be patient, ${TF_BOLD}it won't take long${TF_X} ..."
        # create .please file in $HOME
        [ -f "${PLS_FILE}" ] || touch "${PLS_FILE}"
        # backup .bashrc
        echo -e "${PLS_MSG_PREFIX} be sure ${TF_BOLD}I will backup${TF_X} ${PLS_BASHRC} !"
        [ -f "${PLS_BASHRC}" ] && cp "${PLS_BASHRC}" "${PLS_BASHRC}_backup"
        # append alias to .bashrc
        echo -e "\n\n${PLS_ALIAS}" >> "${PLS_BASHRC}"
        echo -e "${PLS_MSG_PREFIX} ${TF_BOLD}has been installed!${TF_X} Just ${TF_BLINK}${TF_RED}start ${TF_BOLD}a fresh terminal${TF_X} to use ${PLS_MSG_PREFIX}"
        exit 0
    fi
}

# FUNCTION: uninstall
function pls_uninstall() {
    if ! pls_is_installed; then
        echo -e "${PLS_MSG_PREFIX} is apparently ${TF_BOLD}not installed!${TF_X}"
        echo -e "${PLS_MSG_PREFIX} run ${TF_RED}'./please install yourself'${TF_X} from where you put the ${PLS_MSG_PREFIX} script!"
        exit 1
    fi
    # ask for confirmation
    echo -e -n "${PLS_MSG_PREFIX} do you ${TF_BLINK}${TF_BOLD}really${TF_X} want me to uninstall myself? ${TF_BOLD}${TF_RED}(y/n)${TF_X}"
    read -p " " -n 1 -r
    echo
    if [[ ${REPLY} =~ ^[Yy]$ ]]; then
        # uninstall...
        # backup .bashrc
        echo -e "${PLS_MSG_PREFIX} be sure ${TF_BOLD}I will backup${TF_X} ${PLS_BASHRC} !"
        [ -f "${PLS_BASHRC}" ] && cp "${PLS_BASHRC}" "${PLS_BASHRC}_backup"
        # remove alias line from .bashrc
        grep -v -F "${PLS_ALIAS}" "${PLS_BASHRC}" > "/tmp/pleasetmp"  
        mv "/tmp/pleasetmp" "${PLS_BASHRC}"
        # inform that .please file will be kept
        echo -e "${PLS_MSG_PREFIX} be aware that${TF_GREEN} ${PLS_FILE} ${TF_X}will ${TF_BOLD}not${TF_X} be deleted. Just in case :)"
        exit 0
    fi
    echo -e "${PLS_MSG_PREFIX} don't change your mind again!"
    exit 0
}

# FUNCTION: note how to
function pls_note() {
    # if no description entered, show help
    [[ ${@#} = 0 ]] && pls_help && exit 1
    # read param and remove delimiter if present (very unlikely)
    PLS_NEW_DESC=$(echo "$@" | sed "s/$PLS_DELIMITER/ /")
    # remove newlines from description
    PLS_NEW_DESC=${PLS_NEW_DESC//'\n'/' '}
    # ask for one-liner to note
    echo -e -n "${PLS_MSG_PREFIX}${TF_DIM} How do you ${TF_X}${TF_BOLD}${PLS_NEW_DESC}${TF_X}?${TF_GREEN} >"
    read -p " " PLS_NEW_CMD
    # append to .please file
    echo "${PLS_NEW_DESC}${PLS_DELIMITER}${PLS_NEW_CMD//'\n'/' '}" >> "${PLS_FILE}"
    echo -e "${PLS_MSG_PREFIX} ${TF_DIM}I noted it down for you. Don't mention it.${TF_X}"
    exit 0
}

# FUNCTION: look for
function pls_look() {
    # if nothing entered, show help
    [[ ${@#} = 0 ]] && pls_help && exit 1
    # read param
    PLS_LOOK_FOR="$@"
    # look for keyword(s)
    MATCHES=$(grep -F "$PLS_LOOK_FOR" "$PLS_FILE")
    if [[ ${MATCHES#} < 1 ]]; then
        echo -e "${PLS_MSG_PREFIX} don't be angry, but ${TF_BOLD}I didn't find anything${TF_X} :("
    else
        echo -e "${PLS_MSG_PREFIX}${TF_DIM} look at these beautiful memories! ${TF_X}${TF_BOLD}We noted how to ...${TF_X}"
        echo -e "$MATCHES" | \
            while IFS= read line; do
                echo -e "  ${TF_BOLD}${TF_GREEN}⤳${TF_XC} ${line//$PLS_DELIMITER/$PLS_DELIMITER$TF_X$TF_GREEN}${TF_X}"
            done
    fi
    exit 0
}

#
#    PARSE ARGS
#

# TEST: no args?
[ $# -eq 0 ] && pls_help && exit 1

# TEST: install?
[ "$1" = "install" ] && [ "$2" = "yourself" ] && pls_install

# TEST: uninstall?
[ "$1" = "uninstall" ] && [ "$2" = "yourself" ] && pls_uninstall

# TEST: note?
[ "$1" = "note" ] && [ "$2" = "how" ] && [ "$3" = "to" ] && pls_note "${@:4}"

# TEST: look for?
[ "$1" = "look" ] && [ "$2" = "for" ] && pls_look "${@:3}"

# TEST: just checkin'?
[ "$1" = "help" ] && pls_help && exit 0

# TEST: just checkin'?
[ "$1" = "please" ] && echo -e "${PLS_MSG_PREFIX} no begging, please!" && exit 0

# ELSE ...
pls_help
exit 1